version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - "./cakephp:/cakephp:z"
      - "./nginx.conf:/etc/nginx/conf.d/default.conf:z"
    depends_on:
      - php
      - mysql

  php:
    build: php
    volumes:
      - "./cakephp:/cakephp:z"

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=dba
      - MYSQL_DATABASE=swsec
      - MYSQL_USER=www_user
      - MYSQL_PASSWORD=abcde
    volumes:
      - "./dump.sql:/docker-entrypoint-initdb.d/dump.sql:z"
